### ISSUE TITLE
전표처리-일괄처리 정기간행물

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#211]
메뉴: 전표처리-일괄처리 정기간행물

증상 : 권당 가격 입력 --> 금액조회 단추 선택 --> 오류 팝업창 출력

<img width="1296" height="848" alt="Image" src="https://github.com/user-attachments/assets/a6b8804e-07d4-448f-9745-43db242d1608" />

**Comment by vnadvance** [comment]
Fixed in version v0.0.61

**Comment by boazseong** [comment]
Great!

다음 수정사항 
True, Faulse 값 체크 박스로 바꾸어주세요.

<img width="1711" height="843" alt="Image" src="https://github.com/user-attachments/assets/a219df74-c526-4f95-a367-e69f685ee1ea" />

**Comment by boazseong** [comment]
타 기관 테스트 중 아래와 같은 오류가 떴습니다.

<img width="798" height="536" alt="Image" src="https://github.com/user-attachments/assets/e31250db-993d-44b4-88c5-c1562d91dcd7" />

**Comment by skysanchek** [comment]
it is partially fixed.
I can input every detail correctly, and saved but It can not be saved.
there was sent bug report.

**Comment by tienemctai** [comment]
I don't fully understand, can you please send me a recording of the screen?

**Comment by boazseong** [comment]
He said that the main function works well. 
But asking to show pop-up message with saved well. 
Currently, there is no confirmation notice popup when the user push [save] button, he tried push three times and it saved three time. 

Fix: once the user push the [save] button and show popup message with "#Number로 저장되었습니다."

**Comment by skysanchek** [comment]
![Image](https://github.com/user-attachments/assets/bdc9ffd3-9c93-4f9d-92d8-38bfc1f49488)

message show just 1로 저장되었습니다.  but it is better with other slip's saving notice format. 
1번 전표로 저장되었습니다.

**Comment by tienemctai** [comment]
Please check with v0.0.100
